{
 "title": "Jmix 2.x",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"},instance)"
    }
   },
   {
    "name": "view",
    "label": "View",
    "query": {
     "query": "label_values(jmix_ui_views_seconds_max{application=\"$application\", instance=~\"$instance\"},view)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Common metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "View Time(MAX)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (instance)(sum by(view, instance) (jmix_ui_views_seconds_max{application=\"$application\", instance=~\"$instance\", view!~\".*Fragment\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View Data Loading(MAX)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (instance)(max by(view,instance) (jmix_ui_data_seconds_max{application=\"$application\", instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tomcat active sessions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions{application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "HTTP"
    },
    {
     "expr": "sum(rate(jmix_ui_views_seconds_count{application=\"$application\", instance=~\"$instance\", lifeCycle=\"init\"}[1m]))",
     "legendFormat": "JMIX"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=~\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=~\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=~\"$instance\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    },
    {
     "expr": "sum (rate(jmix_ui_views_seconds_sum{application=\"$application\", instance=~\"$instance\"}[5m]))/sum (rate(jmix_ui_views_seconds_count{application=\"$application\", instance=~\"$instance\", lifeCycle=\"beforeShow\"}[5m])) ",
     "legendFormat": "Jmix Views - AVG"
    },
    {
     "expr": "max(sum by (screen) (jmix_ui_views_seconds_max{application=\"$application\"}))",
     "legendFormat": "Jmix Views - MAX"
    }
   ]
  },
  { "title": "Requests of all views", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Views Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(view) (rate(jmix_ui_views_seconds_count{application=\"$application\", instance=~\"$instance\", view!~\".*Fragment\", lifeCycle=\"create\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Views Opening Average Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (view) (rate(jmix_ui_views_seconds_sum{application=\"$application\", instance=~\"$instance\", view!~\".*Fragment\", lifeCycle=~\"beforeShow|create|init|inject|load|ready\"}[5m]))/sum by (view) (rate(jmix_ui_views_seconds_count{application=\"$application\", instance=~\"$instance\", lifeCycle=\"beforeShow\", view!~\".*Fragment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Views Closing Average Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (view) (rate(jmix_ui_views_seconds_sum{application=\"$application\", instance=~\"$instance\", view!~\".*Fragment\", lifeCycle=~\"afterClose|beforeClose\"}[5m]))/sum by (view) (rate(jmix_ui_views_seconds_count{application=\"$application\", instance=~\"$instance\", lifeCycle=\"beforeClose\", view!~\".*Fragment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Views Opening Max Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (view)(sum by(view,instance) (jmix_ui_views_seconds_max{application=\"$application\", instance=~\"$instance\", view!~\".*Fragment\", lifeCycle=~\"beforeShow|create|init|inject|load|ready\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Views Closing Max Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (view)(sum by(view,instance) (jmix_ui_views_seconds_max{application=\"$application\", instance=~\"$instance\", view!~\".*Fragment\", lifeCycle=~\"afterClose|beforeClose\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Views Opening Max Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (view)(sum by(view,instance) (jmix_ui_views_seconds_max{application=\"$application\", instance=~\"$instance\", view!~\".*Fragment\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAX Data Load ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (view, dataLoader)(jmix_ui_data_seconds_max{application=\"$application\", instance=~\"$instance\",lifeCycle=\"load\"})",
     "legendFormat": "{{view}}-{{dataLoader}}"
    }
   ]
  },
  {
   "title": "AVG Data Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (view, dataLoader)(rate(jmix_ui_data_seconds_sum{application=\"$application\", instance=~\"$instance\", lifeCycle=\"load\"}[5m]))/sum by (view, dataLoader)(rate(jmix_ui_data_seconds_count{application=\"$application\", instance=~\"$instance\", lifeCycle=\"load\"}[5m]))",
     "legendFormat": "{{view}}-{{dataLoader}}"
    }
   ]
  },
  { "title": "Requsts by view type - $view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Views Requests Rate - $view",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(view) (rate(jmix_ui_views_seconds_count{application=\"$application\", instance=~\"$instance\", view=\"$view\", lifeCycle=\"create\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Views Duration - $view",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (view) (rate(jmix_ui_views_seconds_sum{application=\"$application\", instance=~\"$instance\", view=\"$view\"}[5m]))/sum by(view) (rate(jmix_ui_views_seconds_count{application=\"$application\", instance=~\"$instance\", lifeCycle=\"beforeShow\", view=\"$view\"}[5m]))",
     "legendFormat": "{{view}}-AVG"
    },
    {
     "expr": "max by (view)(sum by(view,instance) (jmix_ui_views_seconds_max{application=\"$application\", instance=~\"$instance\", view=\"$view\"}))",
     "legendFormat": "{{view}}-MAX"
    }
   ]
  },
  {
   "title": "AVG Duration by Lifecycle - $view",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(lifeCycle)(rate(jmix_ui_views_seconds_sum{application=\"$application\", instance=~\"$instance\", view=\"$view\"}[5m]))/ sum by (lifeCycle)(rate(jmix_ui_views_seconds_count{application=\"$application\", instance=~\"$instance\", view=\"$view\"}[5m]))",
     "legendFormat": "{{lifeCycle}}"
    }
   ]
  },
  {
   "title": "Max Duration by Lifecycle - $view",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(lifeCycle)(jmix_ui_views_seconds_max{application=\"$application\", instance=~\"$instance\", view=\"$view\"})",
     "legendFormat": "{{lifeCycle}}"
    }
   ]
  },
  {
   "title": "AVG Data Loading Time - $view",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (dataLoader, lifeCycle)(rate(jmix_ui_data_seconds_sum{application=\"$application\", instance=~\"$instance\", view=\"$view\"}[5m]))/sum by (dataLoader, lifeCycle)(rate(jmix_ui_data_seconds_count{application=\"$application\", instance=~\"$instance\", view=\"$view\"}[5m]))",
     "legendFormat": "{{dataLoader}}-{{lifeCycle}}"
    }
   ]
  },
  {
   "title": "MAX Data Loading Time - $view",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(dataLoader, lifeCycle)(jmix_ui_data_seconds_max{application=\"$application\", instance=~\"$instance\", view=\"$view\"})",
     "legendFormat": "{{dataLoader}}-{{lifeCycle}}"
    }
   ]
  }
 ]
}