{
 "title": "Jmix 1.x",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"},instance)"
    }
   },
   {
    "name": "screen",
    "label": "Screen",
    "query": {
     "query": "label_values(jmix_ui_screens_seconds_max{application=\"$application\", instance=~\"$instance\"},screen)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Common metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Menu Items(MAX)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (instance)(jmix_ui_menu_seconds_max{application=\"$application\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Screens(MAX)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (instance)(sum by(screen, instance) (jmix_ui_screens_seconds_max{application=\"$application\", instance=~\"$instance\", screen!~\".*Fragment\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Screen Data Load Max",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (instance)(max by(screen,instance) (jmix_ui_data_seconds_max{application=\"$application\", instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tomcat current sessions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions{application=\"$application\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Menu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Menu Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (menuItem) (rate(jmix_ui_menu_seconds_count{application=\"$application\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{menuItem}}"
      }
     ]
    },
    {
     "title": "Menu Average Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (menuItem) (rate(jmix_ui_menu_seconds_sum{application=\"$application\", instance=~\"$instance\"}[5m]))/sum by (menuItem) (rate(jmix_ui_menu_seconds_count{application=\"$application\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{menuItem}}"
      }
     ]
    },
    {
     "title": "Menu Max Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(menuItem)(jmix_ui_menu_seconds_max{application=\"$application\", instance=~\"$instance\"})",
       "legendFormat": "{{menuItem}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests of all screens",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Screens Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 461 },
     "targets": [
      {
       "expr": "sum by(screen) (rate(jmix_ui_screens_seconds_count{application=\"$application\", instance=~\"$instance\", screen!~\".*Fragment\", lifeCycle=\"create\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Screens Average Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 470 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (screen) (rate(jmix_ui_screens_seconds_sum{application=\"$application\", instance=~\"$instance\", screen!~\".*Fragment\"}[5m]))/sum by (screen) (rate(jmix_ui_screens_seconds_count{application=\"$application\", instance=~\"$instance\", lifeCycle=\"beforeShow\", screen!~\".*Fragment\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Screens Max Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 480 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (screen)(sum by(screen,instance) (jmix_ui_screens_seconds_max{application=\"$application\", instance=~\"$instance\", screen!~\".*Fragment\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MAX data load ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 489 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (screen, dataLoader)(jmix_ui_data_seconds_max{application=\"$application\", instance=~\"$instance\",lifeCycle=\"load\"})",
       "legendFormat": "{{screen}}-{{dataLoader}}"
      }
     ]
    },
    {
     "title": "AVG data load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 496 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (screen, dataLoader)(rate(jmix_ui_data_seconds_sum{application=\"$application\", instance=~\"$instance\", lifeCycle=\"load\"}[5m]))/sum by (screen, dataLoader)(rate(jmix_ui_data_seconds_count{application=\"$application\", instance=~\"$instance\", lifeCycle=\"load\"}[5m]))",
       "legendFormat": "{{screen}}-{{dataLoader}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requsts by screen type - $screen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Screens Requests Rate - $screen",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by(screen) (rate(jmix_ui_screens_seconds_count{application=\"$application\", instance=~\"$instance\", screen=\"$screen\", lifeCycle=\"create\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Screens Duration - $screen",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (screen) (rate(jmix_ui_screens_seconds_sum{application=\"$application\", instance=~\"$instance\", screen=\"$screen\"}[5m]))/sum by(screen) (rate(jmix_ui_screens_seconds_count{application=\"$application\", instance=~\"$instance\", lifeCycle=\"beforeShow\", screen=\"$screen\"}[5m]))",
       "legendFormat": "{{screen}}-AVG"
      },
      {
       "expr": "max by (screen)(sum by(screen,instance) (jmix_ui_screens_seconds_max{application=\"$application\", instance=~\"$instance\", screen=\"$screen\"}))",
       "legendFormat": "{{screen}}-MAX"
      }
     ]
    },
    {
     "title": "AVG duration by lifeCycle - $screen",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(lifeCycle)(rate(jmix_ui_screens_seconds_sum{application=\"$application\", instance=~\"$instance\", screen=\"$screen\"}[5m]))/ sum by (lifeCycle)(rate(jmix_ui_screens_seconds_count{application=\"$application\", instance=~\"$instance\", screen=\"$screen\"}[5m]))",
       "legendFormat": "{{lifeCycle}}"
      }
     ]
    },
    {
     "title": "Max duration by lifeCycle - $screen",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(lifeCycle)(jmix_ui_screens_seconds_max{application=\"$application\", instance=~\"$instance\", screen=\"$screen\"})",
       "legendFormat": "{{lifeCycle}}"
      }
     ]
    },
    {
     "title": "AVG data load - $screen",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (dataLoader, lifeCycle)(rate(jmix_ui_data_seconds_sum{application=\"$application\", instance=~\"$instance\", screen=\"$screen\"}[5m]))/sum by (dataLoader, lifeCycle)(rate(jmix_ui_data_seconds_count{application=\"$application\", instance=~\"$instance\", screen=\"$screen\"}[5m]))",
       "legendFormat": "{{dataLoader}}-{{lifeCycle}}"
      }
     ]
    },
    {
     "title": "MAX data load - $screen",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by(dataLoader, lifeCycle)(jmix_ui_data_seconds_max{application=\"$application\", instance=~\"$instance\", screen=\"$screen\"})",
       "legendFormat": "{{dataLoader}}-{{lifeCycle}}"
      }
     ]
    }
   ]
  }
 ]
}